#!/bin/bash

set -e

if ! type git > /dev/null
then
    echo "This tool requires Git to be installed."
    exit 1
fi

BRANCHNAME=$(git rev-parse --abbrev-ref HEAD)
TAG=$1

if [ -z "$TAG" ]
then
    echo "Usage: 'gitmergetomaster <tag>'. Example: 'gitmergetomaster 1.0.0'."
    exit 1
fi

git merge master

git checkout master
git merge --squash $BRANCHNAME
git commit
git branch -D $BRANCHNAME

git tag $1

git push --tags
git push origin master